// data/local/ComprobanteEntity.kt
package ar.com.nexofiscal.nexofiscalposv2.db.entity

import androidx.room.Entity
import androidx.room.PrimaryKey
import androidx.room.TypeConverters
import ar.com.nexofiscal.nexofiscalposv2.models.*
import ar.com.nexofiscal.nexofiscalposv2.db.converter.ListIntegerConverter

@Entity(tableName = "comprobantes")
@TypeConverters(ListIntegerConverter::class)

data class ComprobanteEntity(
    @PrimaryKey val id: Int,
    val numero: Int?,
    val cuotas: Int?,
    val clienteId: Int,
    val remito: String?,
    val persona: String?,
    val provinciaId: Int?,
    val fecha: String?,
    val fechaBaja: String?,
    val motivoBaja: String?,
    val hora: String?,
    val fechaProceso: String?,
    val letra: String?,
    val numeroFactura: Int?,
    val prefijoFactura: String?,
    val operacionNegocioId: Int?,
    val retencionIva: Double?,
    val retencionIibb: Double?,
    val retencionGanancias: Double?,
    val porcentajeGanancias: Double?,
    val porcentajeIibb: Double?,
    val porcentajeIva: Double?,
    val noGravado: Double?,
    val importeIva: Double?,
    val total: String?,
    val totalPagado: Double?,
    val condicionVentaId: Int?,
    val descripcionFlete: String?,
    val vendedorId: Int?,
    val recibo: String?,
    val observaciones1: String?,
    val observaciones2: String?,
    val observaciones3: String?,
    val observaciones4: String?,
    val descuento: Double?,
    val descuento1: Double?,
    val descuento2: Double?,
    val descuento3: Double?,
    val descuento4: Double?,
    val iva2: Double?,
    val impresa: Boolean?,
    val cancelado: Boolean?,
    val nombreCliente: String?,
    val direccionCliente: String?,
    val localidadCliente: String?,
    val garantia: String?,
    val concepto: Int?,
    val notas: String?,
    val lineaPagoUltima: String?,
    val relacionTk: String?,
    val totalIibb: Double?,
    val importeIibb: Double?,
    val provinciaCategoriaIibbId: Int?,
    val importeRetenciones: Double?,
    val provinciaIvaProveedorId: Int?,
    val gananciasProveedorId: Int?,
    val importeGanancias: Double?,
    val numeroIibb: String?,
    val numeroGanancias: String?,
    val gananciasProveedor: String?,
    val cae: String?,
    val fechaVencimiento: String?,
    val remitoCliente: String?,
    val textoDolares: String?,
    val comprobanteFinal: String?,
    val numeroGuia1: String?,
    val numeroGuia2: String?,
    val numeroGuia3: String?,
    val tipoAlicuota1: Double?,
    val tipoAlicuota2: Double?,
    val tipoAlicuota3: Double?,
    val importeIva105: Double?,
    val importeIva21: Double?,
    val importeIva0: Double?,
    val noGravadoIva105: Double?,
    val noGravadoIva21: Double?,
    val noGravadoIva0: Double?,
    val direccionEntrega: String?,
    val fechaEntrega: String?,
    val horaEntrega: String?,
    val empresaId: Int?,
    val puntoVenta: Int?,
    val tipoFactura: Int?,
    val tipoDocumento: Int?,
    val numeroDeDocumento: Long?,
    val qr: String?,
    val comprobanteIdBaja: String?,
    val sucursalId: Int?,
    val descuentoTotal: String?,
    val incrementoTotal: String?,
    val tipoComprobanteId: Int?,
    val promociones: List<Int>,
    val formasDePago: List<Int>
)
