package ar.com.nexofiscal.nexofiscalposv2.models

import ar.com.nexofiscal.nexofiscalposv2.screens.Pago
import com.google.gson.annotations.SerializedName

class Comprobante(
    @SerializedName("id") val id: Int,
    var serverId: Int?,
    var localId: Int = 0,
    @SerializedName("numero") val numero: Int?,
    @SerializedName("cuotas") val cuotas: Int?,
    @SerializedName("cliente_id") val clienteId: Int,
    @SerializedName("remito") val remito: String?,
    @SerializedName("persona") val persona: String?,
    @SerializedName("provincia_id") val provinciaId: Int?,
    @SerializedName("fecha") val fecha: String?,
    @SerializedName("fecha_baja") val fechaBaja: String?,
    @SerializedName("motivo_baja") val motivoBaja: String?,
    @SerializedName("hora") val hora: String?,
    @SerializedName("fecha_proceso") val fechaProceso: String?,
    @SerializedName("letra") var letra: String?,
    @SerializedName("numero_factura") val numeroFactura: Int?,
    @SerializedName("prefijo_factura") val prefijoFactura: String?,
    @SerializedName("operacion_negocio_id") val operacionNegocioId: Int?,
    @SerializedName("retencion_iva") val retencionIva: Double?,
    @SerializedName("retencion_iibb") val retencionIibb: Double?,
    @SerializedName("retencion_ganancias") val retencionGanancias: Double?,
    @SerializedName("porcentaje_ganancias") val porcentajeGanancias: Double?,
    @SerializedName("porcentaje_iibb") val porcentajeIibb: Double?,
    @SerializedName("porcentaje_iva") val porcentajeIva: Double?,
    @SerializedName("no_gravado") val noGravado: Double?,
    @SerializedName("importe_iva") val importeIva: Double?,
    @SerializedName("total") val total: String?,
    @SerializedName("total_pagado") val totalPagado: Double?,
    @SerializedName("condicion_venta_id") val condicionVentaId: Int?,
    @SerializedName("descripcion_flete") val descripcionFlete: String?,
    @SerializedName("vendedor_id") val vendedorId: Int?,
    @SerializedName("recibo") val recibo: String?,
    @SerializedName("observaciones_1") val observaciones1: String?,
    @SerializedName("observaciones_2") val observaciones2: String?,
    @SerializedName("observaciones_3") val observaciones3: String?,
    @SerializedName("observaciones_4") val observaciones4: String?,
    @SerializedName("descuento") val descuento: Double?,
    @SerializedName("descuento_1") val descuento1: Double?,
    @SerializedName("descuento_2") val descuento2: Double?,
    @SerializedName("descuento_3") val descuento3: Double?,
    @SerializedName("descuento_4") val descuento4: Double?,
    @SerializedName("iva_2") val iva2: Double?,
    @SerializedName("impresa") val impresa: Boolean?,
    @SerializedName("cancelado") val cancelado: Boolean?,
    @SerializedName("nombre_cliente") val nombreCliente: String?,
    @SerializedName("direccion_cliente") val direccionCliente: String?,
    @SerializedName("localidad_cliente") val localidadCliente: String?,
    @SerializedName("garantia") val garantia: String?,
    @SerializedName("concepto") val concepto: Int?,
    @SerializedName("notas") val notas: String?,
    @SerializedName("linea_pago_ultima") val lineaPagoUltima: String?,
    @SerializedName("relacion_tk") val relacionTk: String?,
    @SerializedName("total_iibb") val totalIibb: Double?,
    @SerializedName("importe_iibb") val importeIibb: Double?,
    @SerializedName("provincia_categoria_iibb_id") val provinciaCategoriaIibbId: Int?,
    @SerializedName("importe_retenciones") val importeRetenciones: Double?,
    @SerializedName("provincia_iva_proveedor_id") val provinciaIvaProveedorId: Int?,
    @SerializedName("ganancias_proveedor_id") val gananciasProveedorId: Int?,
    @SerializedName("importe_ganancias") val importeGanancias: Double?,
    @SerializedName("numero_iibb") val numeroIibb: String?,
    @SerializedName("numero_ganancias") val numeroGanancias: String?,
    @SerializedName("ganancias_proveedor") val gananciasProveedor: String?,
    @SerializedName("cae") val cae: String?,
    @SerializedName("fecha_vencimiento") val fechaVencimiento: String?,
    @SerializedName("remito_cliente") val remitoCliente: String?,
    @SerializedName("texto_dolares") val textoDolares: String?,
    @SerializedName("comprobante_final") val comprobanteFinal: String?,
    @SerializedName("numero_guia_1") val numeroGuia1: String?,
    @SerializedName("numero_guia_2") val numeroGuia2: String?,
    @SerializedName("numero_guia_3") val numeroGuia3: String?,
    @SerializedName("tipo_alicuota_1") val tipoAlicuota1: Double?,
    @SerializedName("tipo_alicuota_2") val tipoAlicuota2: Double?,
    @SerializedName("tipo_alicuota_3") val tipoAlicuota3: Double?,
    @SerializedName("importe_iva_105") val importeIva105: Double?,
    @SerializedName("importe_iva_21") val importeIva21: Double?,
    @SerializedName("importe_iva_0") val importeIva0: Double?,
    @SerializedName("no_gravado_iva_105") val noGravadoIva105: Double?,
    @SerializedName("no_gravado_iva_21") val noGravadoIva21: Double?,
    @SerializedName("no_gravado_iva_0") val noGravadoIva0: Double?,
    @SerializedName("direccion_entrega") val direccionEntrega: String?,
    @SerializedName("fecha_entrega") val fechaEntrega: String?,
    @SerializedName("hora_entrega") val horaEntrega: String?,
    @SerializedName("empresa_id") val empresaId: Int?,
    @SerializedName("usuario_id") val usuarioId: Int? = null, // Nuevo campo opcional
    @SerializedName("punto_venta") val puntoVenta: Int?,
    @SerializedName("tipo_factura") var tipoFactura: Int?,
    @SerializedName("tipo_documento") val tipoDocumento: Int?,
    @SerializedName("numero_de_documento") val numeroDeDocumento: Long?,
    @SerializedName("qr") val qr: String?,
    @SerializedName("comprobante_id_baja") val comprobanteIdBaja: String?,
    @SerializedName("sucursal_id") val sucursalId: Int?,
    @SerializedName("descuento_total") val descuentoTotal: String?,
    @SerializedName("incremento_total") val incrementoTotal: String?,
    @SerializedName("cliente") val cliente: Cliente?,
    @SerializedName("vendedor") val vendedor: Vendedor?,
    @SerializedName("provincia") val provincia: Provincia?,
    @SerializedName("tipo_comprobante") val tipoComprobante: TipoComprobante?,
    @SerializedName("promociones")
    var promociones: List<Promocion>?,

    @SerializedName("formas_de_pago")
    var formas_de_pago: List<FormaPagoComprobante>,
    var tipoComprobanteId: Int?
) {
    @SerializedName("cierre_caja_id")
    var cierreCajaId: Int? = null

    override fun toString(): String {
        return "Comprobante(id=$id, numero=$numero, numeroFactura=$numeroFactura)"
    }

    fun copy(
        id: Int = this.id,
        serverId: Int? = this.serverId,
        localId: Int = this.localId,
        numero: Int? = this.numero,
        cuotas: Int? = this.cuotas,
        clienteId: Int = this.clienteId,
        remito: String? = this.remito,
        persona: String? = this.persona,
        provinciaId: Int? = this.provinciaId,
        fecha: String? = this.fecha,
        fechaBaja: String? = this.fechaBaja,
        motivoBaja: String? = this.motivoBaja,
        hora: String? = this.hora,
        fechaProceso: String? = this.fechaProceso,
        letra: String? = this.letra,
        numeroFactura: Int? = this.numeroFactura,
        prefijoFactura: String? = this.prefijoFactura,
        operacionNegocioId: Int? = this.operacionNegocioId,
        retencionIva: Double? = this.retencionIva,
        retencionIibb: Double? = this.retencionIibb,
        retencionGanancias: Double? = this.retencionGanancias,
        porcentajeGanancias: Double? = this.porcentajeGanancias,
        porcentajeIibb: Double? = this.porcentajeIibb,
        porcentajeIva: Double? = this.porcentajeIva,
        noGravado: Double? = this.noGravado,
        importeIva: Double? = this.importeIva,
        total: String? = this.total,
        totalPagado: Double? = this.totalPagado,
        condicionVentaId: Int? = this.condicionVentaId,
        descripcionFlete: String? = this.descripcionFlete,
        vendedorId: Int? = this.vendedorId,
        recibo: String? = this.recibo,
        observaciones1: String? = this.observaciones1,
        observaciones2: String? = this.observaciones2,
        observaciones3: String? = this.observaciones3,
        observaciones4: String? = this.observaciones4,
        descuento: Double? = this.descuento,
        descuento1: Double? = this.descuento1,
        descuento2: Double? = this.descuento2,
        descuento3: Double? = this.descuento3,
        descuento4: Double? = this.descuento4,
        iva2: Double? = this.iva2,
        impresa: Boolean? = this.impresa,
        cancelado: Boolean? = this.cancelado,
        nombreCliente: String? = this.nombreCliente,
        direccionCliente: String? = this.direccionCliente,
        localidadCliente: String? = this.localidadCliente,
        garantia: String? = this.garantia,
        concepto: Int? = this.concepto,
        notas: String? = this.notas,
        lineaPagoUltima: String? = this.lineaPagoUltima,
        relacionTk: String? = this.relacionTk,
        totalIibb: Double? = this.totalIibb,
        importeIibb: Double? = this.importeIibb,
        provinciaCategoriaIibbId: Int? = this.provinciaCategoriaIibbId,
        importeRetenciones: Double? = this.importeRetenciones,
        provinciaIvaProveedorId: Int? = this.provinciaIvaProveedorId,
        gananciasProveedorId: Int? = this.gananciasProveedorId,
        importeGanancias: Double? = this.importeGanancias,
        numeroIibb: String? = this.numeroIibb,
        numeroGanancias: String? = this.numeroGanancias,
        gananciasProveedor: String? = this.gananciasProveedor,
        cae: String? = this.cae,
        fechaVencimiento: String? = this.fechaVencimiento,
        remitoCliente: String? = this.remitoCliente,
        textoDolares: String? = this.textoDolares,
        comprobanteFinal: String? = this.comprobanteFinal,
        numeroGuia1: String? = this.numeroGuia1,
        numeroGuia2: String? = this.numeroGuia2,
        numeroGuia3: String? = this.numeroGuia3,
        tipoAlicuota1: Double? = this.tipoAlicuota1,
        tipoAlicuota2: Double? = this.tipoAlicuota2,
        tipoAlicuota3: Double? = this.tipoAlicuota3,
        importeIva105: Double? = this.importeIva105,
        importeIva21: Double? = this.importeIva21,
        importeIva0: Double? = this.importeIva0,
        noGravadoIva105: Double? = this.noGravadoIva105,
        noGravadoIva21: Double? = this.noGravadoIva21,
        noGravadoIva0: Double? = this.noGravadoIva0,
        direccionEntrega: String? = this.direccionEntrega,
        fechaEntrega: String? = this.fechaEntrega,
        horaEntrega: String? = this.horaEntrega,
        empresaId: Int? = this.empresaId,
        usuarioId: Int? = null, // Nuevo campo opcional
        puntoVenta: Int? = this.puntoVenta,
        tipoFactura: Int? = this.tipoFactura,
        tipoDocumento: Int? = this.tipoDocumento,
        numeroDeDocumento: Long? = this.numeroDeDocumento,
        qr: String? = this.qr,
        comprobanteIdBaja: String? = this.comprobanteIdBaja,
        sucursalId: Int? = this.sucursalId,
        descuentoTotal: String? = this.descuentoTotal,
        incrementoTotal: String? = this.incrementoTotal,
        cliente: Cliente? = this.cliente,
        vendedor: Vendedor? = this.vendedor,
        provincia: Provincia? = this.provincia,
        tipoComprobante: TipoComprobante? = this.tipoComprobante,
        promociones: List<Promocion>? = this.promociones,
        formas_de_pago: List<FormaPagoComprobante>? = this.formas_de_pago,
        tipoComprobanteId: Int? = this.tipoComprobanteId
    ): Comprobante {
        return Comprobante(
            id, serverId, localId, numero, cuotas, clienteId, remito, persona, provinciaId,
            fecha, fechaBaja, motivoBaja, hora, fechaProceso, letra, numeroFactura,
            prefijoFactura, operacionNegocioId, retencionIva, retencionIibb, retencionGanancias,
            porcentajeGanancias, porcentajeIibb, porcentajeIva, noGravado, importeIva, total,
            totalPagado, condicionVentaId, descripcionFlete, vendedorId, recibo, observaciones1,
            observaciones2, observaciones3, observaciones4, descuento, descuento1, descuento2,
            descuento3, descuento4, iva2, impresa, cancelado, nombreCliente, direccionCliente,
            localidadCliente, garantia, concepto, notas, lineaPagoUltima, relacionTk, totalIibb,
            importeIibb, provinciaCategoriaIibbId, importeRetenciones, provinciaIvaProveedorId,
            gananciasProveedorId, importeGanancias, numeroIibb, numeroGanancias, gananciasProveedor,
            cae, fechaVencimiento, remitoCliente, textoDolares, comprobanteFinal, numeroGuia1,
            numeroGuia2, numeroGuia3, tipoAlicuota1, tipoAlicuota2, tipoAlicuota3, importeIva105,
            importeIva21, importeIva0, noGravadoIva105, noGravadoIva21, noGravadoIva0,
            direccionEntrega, fechaEntrega, horaEntrega, empresaId, usuarioId, puntoVenta,
            tipoFactura, tipoDocumento, numeroDeDocumento, qr, comprobanteIdBaja, sucursalId,
            descuentoTotal, incrementoTotal, cliente, vendedor, provincia, tipoComprobante,
            promociones, formas_de_pago!!, tipoComprobanteId
        )
    }
}