package ar.com.nexofiscal.nexofiscalposv2.models

import com.google.gson.annotations.SerializedName

/**
 * DTO (Data Transfer Object) para subir un Comprobante a la API.
 * Contiene todos los campos necesarios para la creación/actualización.
 */
data class ComprobanteUploadRequest(
    @SerializedName("numero") val numero: Int?,
    @SerializedName("cuotas") val cuotas: Int?,
    @SerializedName("cliente_id") val clienteId: Int,
    @SerializedName("remito") val remito: String?,
    @SerializedName("persona") val persona: String?,
    @SerializedName("provincia_id") val provinciaId: Int?,
    @SerializedName("fecha") val fecha: String?,
    @SerializedName("fecha_baja") val fechaBaja: String?,
    @SerializedName("motivo_baja") val motivoBaja: String?,
    @SerializedName("hora") val hora: String?,
    @SerializedName("fecha_proceso") val fechaProceso: String?,
    @SerializedName("letra") val letra: String?,
    @SerializedName("numero_factura") val numeroFactura: Int?,
    @SerializedName("prefijo_factura") val prefijoFactura: String?,
    @SerializedName("operacion_negocio_id") val operacionNegocioId: Int?,
    @SerializedName("retencion_iva") val retencionIva: Double?,
    @SerializedName("retencion_iibb") val retencionIibb: Double?,
    @SerializedName("retencion_ganancias") val retencionGanancias: Double?,
    @SerializedName("porcentaje_ganancias") val porcentajeGanancias: Double?,
    @SerializedName("porcentaje_iibb") val porcentajeIibb: Double?,
    @SerializedName("porcentaje_iva") val porcentajeIva: Double?,
    @SerializedName("no_gravado") val noGravado: Double?,
    @SerializedName("importe_iva") val importeIva: Double?,
    @SerializedName("total") val total: String?,
    @SerializedName("total_pagado") val totalPagado: Double?,
    @SerializedName("condicion_venta_id") val condicionVentaId: Int?,
    @SerializedName("descripcion_flete") val descripcionFlete: String?,
    @SerializedName("vendedor_id") val vendedorId: Int?,
    @SerializedName("recibo") val recibo: String?,
    @SerializedName("observaciones_1") val observaciones1: String?,
    @SerializedName("observaciones_2") val observaciones2: String?,
    @SerializedName("observaciones_3") val observaciones3: String?,
    @SerializedName("observaciones_4") val observaciones4: String?,
    @SerializedName("descuento") val descuento: Double?,
    @SerializedName("descuento_1") val descuento1: Double?,
    @SerializedName("descuento_2") val descuento2: Double?,
    @SerializedName("descuento_3") val descuento3: Double?,
    @SerializedName("descuento_4") val descuento4: Double?,
    @SerializedName("iva_2") val iva2: Double?,
    @SerializedName("impresa") val impresa: Boolean?,
    @SerializedName("cancelado") val cancelado: Boolean?,
    @SerializedName("nombre_cliente") val nombreCliente: String?,
    @SerializedName("direccion_cliente") val direccionCliente: String?,
    @SerializedName("localidad_cliente") val localidadCliente: String?,
    @SerializedName("garantia") val garantia: String?,
    @SerializedName("concepto") val concepto: Int?,
    @SerializedName("notas") val notas: String?,
    @SerializedName("linea_pago_ultima") val lineaPagoUltima: String?,
    @SerializedName("relacion_tk") val relacionTk: String?,
    @SerializedName("total_iibb") val totalIibb: Double?,
    @SerializedName("importe_iibb") val importeIibb: Double?,
    @SerializedName("provincia_categoria_iibb_id") val provinciaCategoriaIibbId: Int?,
    @SerializedName("importe_retenciones") val importeRetenciones: Double?,
    @SerializedName("provincia_iva_proveedor_id") val provinciaIvaProveedorId: Int?,
    @SerializedName("ganancias_proveedor_id") val gananciasProveedorId: Int?,
    @SerializedName("importe_ganancias") val importeGanancias: Double?,
    @SerializedName("numero_iibb") val numeroIibb: String?,
    @SerializedName("numero_ganancias") val numeroGanancias: String?,
    @SerializedName("ganancias_proveedor") val gananciasProveedor: String?,
    @SerializedName("cae") val cae: String?,
    @SerializedName("fecha_vencimiento") val fechaVencimiento: String?,
    @SerializedName("remito_cliente") val remitoCliente: String?,
    @SerializedName("texto_dolares") val textoDolares: String?,
    @SerializedName("comprobante_final") val comprobanteFinal: String?,
    @SerializedName("numero_guia_1") val numeroGuia1: String?,
    @SerializedName("numero_guia_2") val numeroGuia2: String?,
    @SerializedName("numero_guia_3") val numeroGuia3: String?,
    @SerializedName("tipo_alicuota_1") val tipoAlicuota1: Double?,
    @SerializedName("tipo_alicuota_2") val tipoAlicuota2: Double?,
    @SerializedName("tipo_alicuota_3") val tipoAlicuota3: Double?,
    @SerializedName("importe_iva_105") val importeIva105: Double?,
    @SerializedName("importe_iva_21") val importeIva21: Double?,
    @SerializedName("importe_iva_0") val importeIva0: Double?,
    @SerializedName("no_gravado_iva_105") val noGravadoIva105: Double?,
    @SerializedName("no_gravado_iva_21") val noGravadoIva21: Double?,
    @SerializedName("no_gravado_iva_0") val noGravadoIva0: Double?,
    @SerializedName("direccion_entrega") val direccionEntrega: String?,
    @SerializedName("fecha_entrega") val fechaEntrega: String?,
    @SerializedName("hora_entrega") val horaEntrega: String?,
    @SerializedName("punto_venta") val puntoVenta: Int?,
    @SerializedName("tipo_factura") val tipoFactura: Int?,
    @SerializedName("tipo_documento") val tipoDocumento: Int?,
    @SerializedName("numero_de_documento") val numeroDeDocumento: Long?,
    @SerializedName("qr") val qr: String?,
    @SerializedName("comprobante_id_baja") val comprobanteIdBaja: String?,
    @SerializedName("sucursal_id") val sucursalId: Int?,
    @SerializedName("descuento_total") val descuentoTotal: String?,
    @SerializedName("incremento_total") val incrementoTotal: String?,
    @SerializedName("tipo_comprobante_id") val tipoComprobanteId: Int?,


) {
    data class FormaPagoRequest(
        @SerializedName("id") val id: Int
    )


}